### ISSUE TITLE
Add troubleshooting content

### ISSUE THREAD

**Issue by clebert** [clebert/pageobject#5]
- Chromedriver

**Comment by clebert** [comment]
Travis:

For what it's worth, current (62) chrome stable seems to work correctly in the containerized (sudo: false) trusty environment using Chrome's new --headless mode, which doesn't require xvfb. You just need to install the google-chrome-stable package using the docker package installation, i.e.:

```sh
addons:
  apt:
    packages:
      - google-chrome-stable
```

instead of the documented addon:

```sh
addons:
  chrome: stable
```

**Comment by clebert** [comment]
Travis -> sudo: required

**Comment by clebert** [comment]
Docker:

With latest docker is now possible to set the shm size via docker run option --shm-size=2g where 2g is 2GB but can be changed:
https://docs.docker.com/engine/reference/run/

**Comment by th31nitiate** [comment]
I am personally not experiencing this issue on Travis, I am mainly experiencing it on docker with other components installed. II am able to execute the browser using:  google-chrome  --headless --disable-gpu --dump-dom https://www.chromestatus.com/ 

When I run this with selenium it is no longer properly functional. 

Error retrieving a new session from the selenium server

> Connection refused! Is selenium server started?
> { Error: socket hang up
>     at createHangUpError (_http_client.js:330:15)
>     at Socket.socketCloseListener (_http_client.js:362:23)
>     at emitOne (events.js:130:20)
>     at Socket.emit (events.js:221:7)
>     at TCP._handle.close [as _onclose] (net.js:558:12) code: 'ECONNRESET' }
> 

It is funcational with firefox so it seems like a Chrome thing. It might possibly be a nightwarch thing too. :/

I just thought I would let put info here in case it is useful.
